import Foundation

enum QuestionPool {
    static let seed: [Question] = [
        .init(id: UUID(), question: "Did you check your bank balance this week?",
              whyExplanation: "Avoiding financial information increases anxiety over time. Regular exposure reduces the stress response.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a loss feel worse than a same-sized win felt good?",
              whyExplanation: "We feel losses approximately twice as intensely as equivalent gains. Recognising this helps us make calmer decisions.",
              biasName: "Loss Aversion", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you spend today what was meant for future you?",
              whyExplanation: "Our brains heavily discount future rewards. Naming this helps close the gap between present and future self.",
              biasName: "Present Bias", biasCategory: "Time Perception", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you treat a refund differently to money you earned?",
              whyExplanation: "Money is money regardless of where it came from. Mental accounting tricks us into spending windfalls carelessly.",
              biasName: "Mental Accounting", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a sale price make you spend more than planned?",
              whyExplanation: "The first number we see anchors all decisions that follow. Awareness of anchors reduces their pull.",
              biasName: "Anchoring", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you continue something just because you had already paid?",
              whyExplanation: "Past costs cannot be recovered. Only future value should drive current decisions.",
              biasName: "Sunk Cost Fallacy", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you avoid a financial task because it felt too big?",
              whyExplanation: "Breaking tasks into the smallest possible step reduces avoidance. What is the one minute version of this task?",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did social pressure influence a spending decision?",
              whyExplanation: "We overestimate how much others notice our possessions. Spending for status rarely delivers lasting satisfaction.",
              biasName: "Social Proof", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you feel more confident about money than the facts warranted?",
              whyExplanation: "Overconfidence in financial decisions is common and costly. Checking assumptions before committing reduces risk.",
              biasName: "Overconfidence Bias", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you stick with a default option without questioning it?",
              whyExplanation: "Default options are powerful nudges. Actively choosing rather than accepting defaults keeps you in control.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did scarcity make something feel more valuable?",
              whyExplanation: "Limited availability triggers urgency that bypasses rational evaluation. Pausing 24 hours before scarce offers often reduces desire.",
              biasName: "Scarcity Heuristic", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you round up a small cost to justify a larger one?",
              whyExplanation: "Small amounts matter and accumulate. Dismissing them as negligible is how budgets silently erode.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did an unexpected expense catch you off guard this week?",
              whyExplanation: "Irregular expenses are predictably unpredictable. A small buffer fund converts crises into inconveniences.",
              biasName: "Planning Fallacy", biasCategory: "Time Perception", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you reward yourself with spending after a good financial week?",
              whyExplanation: "Moral licensing allows good behaviour to justify later indulgence. Recognising the pattern interrupts it.",
              biasName: "Moral Licensing", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you make a financial decision while stressed or tired?",
              whyExplanation: "Decision quality drops significantly under stress. High-stakes financial decisions deserve a rested mind.",
              biasName: "Ego Depletion", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),

        // ── Round 2 — expansion for daily rotation (less repetition) ──
        .init(id: UUID(), question: "Did a subscription auto-renew you'd meant to cancel?",
              whyExplanation: "Defaults exploit our inertia. Diarising cancellation windows saves real money over time.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you buy something because 'only a few left'?",
              whyExplanation: "Manufactured scarcity is a sales tactic. Real scarcity is rare in everyday purchases.",
              biasName: "Scarcity Heuristic", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a rough week justify an indulgence you wouldn't otherwise allow?",
              whyExplanation: "Hard weeks are when bias loves us most. Noticing the pattern interrupts it.",
              biasName: "Moral Licensing", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you assume a future you will handle what current you can't?",
              whyExplanation: "Future self bias is the engine of debt. Today's self must make future's constraints real.",
              biasName: "Present Bias", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did a vivid recent memory shape a money decision this week?",
              whyExplanation: "Vivid isn't representative. A quick statistic beats a dramatic story every time.",
              biasName: "Availability Heuristic", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you avoid opening a statement or bill this week?",
              whyExplanation: "Avoidance multiplies costs. Looking is the first step — no action required yet.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did paying by card feel different to paying cash would have?",
              whyExplanation: "Small digital payments add up invisibly. A weekly total, not per-tap, is the real number.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'save 30%' feel more compelling than 'pay 70%'?",
              whyExplanation: "Framing bends identical maths. Restating the deal in absolute dollars reveals the truth.",
              biasName: "Framing Effect", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did a friend's purchase push you toward your own?",
              whyExplanation: "The desire to match peers is ancient and largely invisible. Ask: would I want this if nobody else had it?",
              biasName: "Social Proof", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a big purchase end up costing more than you planned?",
              whyExplanation: "Plans underestimate cost by 30%+ on average. Padding the budget is realism, not pessimism.",
              biasName: "Planning Fallacy", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you keep a subscription because switching felt like effort?",
              whyExplanation: "Status quo bias is quiet and costly. Ten minutes spent auditing can save hundreds a year.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you see a price and accept it without comparing?",
              whyExplanation: "The first price anchors all that follow. Decide your number before seeing theirs.",
              biasName: "Anchoring", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a 'treat money' vs 'bills money' mental split change a choice?",
              whyExplanation: "All dollars spend the same. Mental buckets feel efficient but cost clarity.",
              biasName: "Mental Accounting", biasCategory: "Money Psychology", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you double down on something failing because you'd already committed?",
              whyExplanation: "Past costs are gone. Asking 'would I start this today?' reframes the decision.",
              biasName: "Sunk Cost Fallacy", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did the fear of losing sway you more than the chance of gaining?",
              whyExplanation: "Losses weigh roughly twice as heavily as equivalent gains. Naming this rebalances the scale.",
              biasName: "Loss Aversion", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
    ]
}
