import Foundation

enum QuestionPool {
    static let seed: [Question] = [
        .init(id: UUID(), question: "Did you check your bank balance this week?",
              whyExplanation: "Avoiding financial information increases anxiety over time. Regular exposure reduces the stress response.",
              biasName: "Ostrich Effect", lastShown: nil),
        .init(id: UUID(), question: "Did a loss feel worse than a same-sized win felt good?",
              whyExplanation: "We feel losses approximately twice as intensely as equivalent gains. Recognising this helps us make calmer decisions.",
              biasName: "Loss Aversion", lastShown: nil),
        .init(id: UUID(), question: "Did you spend today what was meant for future you?",
              whyExplanation: "Our brains heavily discount future rewards. Naming this helps close the gap between present and future self.",
              biasName: "Present Bias", lastShown: nil),
        .init(id: UUID(), question: "Did you treat a refund differently to money you earned?",
              whyExplanation: "Money is money regardless of where it came from. Mental accounting tricks us into spending windfalls carelessly.",
              biasName: "Mental Accounting", lastShown: nil),
        .init(id: UUID(), question: "Did a sale price make you spend more than planned?",
              whyExplanation: "The first number we see anchors all decisions that follow. Awareness of anchors reduces their pull.",
              biasName: "Anchoring", lastShown: nil),
        .init(id: UUID(), question: "Did you continue something just because you had already paid?",
              whyExplanation: "Past costs cannot be recovered. Only future value should drive current decisions.",
              biasName: "Sunk Cost Fallacy", lastShown: nil),
        .init(id: UUID(), question: "Did you avoid a financial task because it felt too big?",
              whyExplanation: "Breaking tasks into the smallest possible step reduces avoidance. What is the one minute version of this task?",
              biasName: "Ostrich Effect", lastShown: nil),
        .init(id: UUID(), question: "Did social pressure influence a spending decision?",
              whyExplanation: "We overestimate how much others notice our possessions. Spending for status rarely delivers lasting satisfaction.",
              biasName: "Social Proof", lastShown: nil),
        .init(id: UUID(), question: "Did you feel more confident about money than the facts warranted?",
              whyExplanation: "Overconfidence in financial decisions is common and costly. Checking assumptions before committing reduces risk.",
              biasName: "Overconfidence Bias", lastShown: nil),
        .init(id: UUID(), question: "Did you stick with a default option without questioning it?",
              whyExplanation: "Default options are powerful nudges. Actively choosing rather than accepting defaults keeps you in control.",
              biasName: "Status Quo Bias", lastShown: nil),
        .init(id: UUID(), question: "Did scarcity make something feel more valuable?",
              whyExplanation: "Limited availability triggers urgency that bypasses rational evaluation. Pausing 24 hours before scarce offers often reduces desire.",
              biasName: "Scarcity Heuristic", lastShown: nil),
        .init(id: UUID(), question: "Did you round up a small cost to justify a larger one?",
              whyExplanation: "Small amounts matter and accumulate. Dismissing them as negligible is how budgets silently erode.",
              biasName: "Denomination Effect", lastShown: nil),
        .init(id: UUID(), question: "Did an unexpected expense catch you off guard this week?",
              whyExplanation: "Irregular expenses are predictably unpredictable. A small buffer fund converts crises into inconveniences.",
              biasName: "Planning Fallacy", lastShown: nil),
        .init(id: UUID(), question: "Did you reward yourself with spending after a good financial week?",
              whyExplanation: "Moral licensing allows good behaviour to justify later indulgence. Recognising the pattern interrupts it.",
              biasName: "Moral Licensing", lastShown: nil),
        .init(id: UUID(), question: "Did you make a financial decision while stressed or tired?",
              whyExplanation: "Decision quality drops significantly under stress. High-stakes financial decisions deserve a rested mind.",
              biasName: "Ego Depletion", lastShown: nil)
    ]
}
