import Foundation

enum QuestionPool {
    static let seed: [Question] = [
        .init(id: UUID(), question: "Did you check your bank balance this week?",
              whyExplanation: "Avoiding financial information increases anxiety over time. Regular exposure reduces the stress response.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a loss feel worse than a same-sized win felt good?",
              whyExplanation: "We feel losses approximately twice as intensely as equivalent gains. Recognising this helps us make calmer decisions.",
              biasName: "Loss Aversion", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you spend today what was meant for future you?",
              whyExplanation: "Our brains heavily discount future rewards. Naming this helps close the gap between present and future self.",
              biasName: "Present Bias", biasCategory: "Time Perception", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you treat a refund differently to money you earned?",
              whyExplanation: "Money is money regardless of where it came from. Mental accounting tricks us into spending windfalls carelessly.",
              biasName: "Mental Accounting", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a sale price make you spend more than planned?",
              whyExplanation: "The first number we see anchors all decisions that follow. Awareness of anchors reduces their pull.",
              biasName: "Anchoring", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you continue something just because you had already paid?",
              whyExplanation: "Past costs cannot be recovered. Only future value should drive current decisions.",
              biasName: "Sunk Cost Fallacy", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you avoid a financial task because it felt too big?",
              whyExplanation: "Breaking tasks into the smallest possible step reduces avoidance. What is the one minute version of this task?",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did social pressure influence a spending decision?",
              whyExplanation: "We overestimate how much others notice our possessions. Spending for status rarely delivers lasting satisfaction.",
              biasName: "Social Proof", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you feel more confident about money than the facts warranted?",
              whyExplanation: "Overconfidence in financial decisions is common and costly. Checking assumptions before committing reduces risk.",
              biasName: "Overconfidence Bias", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you stick with a default option without questioning it?",
              whyExplanation: "Default options are powerful nudges. Actively choosing rather than accepting defaults keeps you in control.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'limited time' or 'only a few left' make something feel more valuable?",
              whyExplanation: "Limited availability triggers urgency that bypasses rational evaluation. Pausing 24 hours before scarce offers often reduces desire.",
              biasName: "Scarcity Heuristic", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you round up a small cost to justify a larger one?",
              whyExplanation: "Small amounts matter and accumulate. Dismissing them as negligible is how budgets silently erode.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did an unexpected expense catch you off guard this week?",
              whyExplanation: "Irregular expenses are predictably unpredictable. A small buffer fund converts crises into inconveniences.",
              biasName: "Planning Fallacy", biasCategory: "Time Perception", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you reward yourself with spending after a good financial week?",
              whyExplanation: "Moral licensing allows good behaviour to justify later indulgence. Recognising the pattern interrupts it.",
              biasName: "Moral Licensing", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you make a financial decision while stressed or tired?",
              whyExplanation: "Decision quality drops significantly under stress. High-stakes financial decisions deserve a rested mind.",
              biasName: "Ego Depletion", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),

        // ── Round 2 — expansion for daily rotation (less repetition) ──
        .init(id: UUID(), question: "Did a subscription auto-renew you'd meant to cancel?",
              whyExplanation: "Defaults exploit our inertia. Diarising cancellation windows saves real money over time.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you buy something because 'only a few left'?",
              whyExplanation: "Manufactured scarcity is a sales tactic. Real scarcity is rare in everyday purchases.",
              biasName: "Scarcity Heuristic", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a rough week justify an indulgence you wouldn't otherwise allow?",
              whyExplanation: "Hard weeks are when bias loves us most. Noticing the pattern interrupts it.",
              biasName: "Moral Licensing", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you assume a future you will handle what current you can't?",
              whyExplanation: "Future self bias is the engine of debt. Today's self must make future's constraints real.",
              biasName: "Present Bias", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did a vivid recent memory shape a money decision this week?",
              whyExplanation: "Vivid isn't representative. A quick statistic beats a dramatic story every time.",
              biasName: "Availability Heuristic", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you avoid opening a statement or bill this week?",
              whyExplanation: "Avoidance multiplies costs. Looking is the first step — no action required yet.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did paying by card feel different to paying cash would have?",
              whyExplanation: "Small digital payments add up invisibly. A weekly total, not per-tap, is the real number.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'save 30%' feel more compelling than 'pay 70%'?",
              whyExplanation: "Framing bends identical maths. Restating the deal in absolute dollars reveals the truth.",
              biasName: "Framing Effect", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did seeing a friend buy something make you want one too?",
              whyExplanation: "The desire to match peers is ancient and largely invisible. Ask: would I want this if nobody else had it?",
              biasName: "Social Proof", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a big purchase end up costing more than you planned?",
              whyExplanation: "Plans underestimate cost by 30%+ on average. Padding the budget is realism, not pessimism.",
              biasName: "Planning Fallacy", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you keep a subscription because switching felt like effort?",
              whyExplanation: "Status quo bias is quiet and costly. Ten minutes spent auditing can save hundreds a year.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you see a price and accept it without comparing?",
              whyExplanation: "The first price anchors all that follow. Decide your number before seeing theirs.",
              biasName: "Anchoring", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a 'treat money' vs 'bills money' mental split change a choice?",
              whyExplanation: "All dollars spend the same. Mental buckets feel efficient but cost clarity.",
              biasName: "Mental Accounting", biasCategory: "Money Psychology", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you double down on something failing because you'd already committed?",
              whyExplanation: "Past costs are gone. Asking 'would I start this today?' reframes the decision.",
              biasName: "Sunk Cost Fallacy", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did the fear of losing sway you more than the chance of gaining?",
              whyExplanation: "Losses weigh roughly twice as heavily as equivalent gains. Naming this rebalances the scale.",
              biasName: "Loss Aversion", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),

        // ── Round 3 — expansion to ~60 for long rotation ──
        .init(id: UUID(), question: "Did you set a budget this month but spend past it?",
              whyExplanation: "Intentions rarely beat environment. The fix is smaller friction, not stronger resolve.",
              biasName: "Planning Fallacy", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did a purchase feel smaller because it came in small increments?",
              whyExplanation: "Weekly coffees add up to hundreds. Annualising the spend reveals the real number.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you say 'I'll earn it back' when making a discretionary spend?",
              whyExplanation: "Future income is uncertain. Today's constraints should drive today's choices.",
              biasName: "Overconfidence Bias", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you ignore a bank notification you suspected was bad news?",
              whyExplanation: "Looking is the hard part. The numbers don't change because you haven't seen them.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you accept a 'same price' offer without checking alternatives?",
              whyExplanation: "The reference price stuck. Five minutes of shopping around recalibrates the anchor.",
              biasName: "Anchoring", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a limited-time offer change what you bought?",
              whyExplanation: "Scarcity is mostly marketing. Real scarcity rarely expires in an hour.",
              biasName: "Scarcity Heuristic", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'I've already paid for membership' justify buying more?",
              whyExplanation: "Sunk costs can't come back. Only fresh value should drive fresh spending.",
              biasName: "Sunk Cost Fallacy", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did a tired evening decision cost you more than a rested one would?",
              whyExplanation: "Willpower drains across the day. Big choices deserve morning clarity.",
              biasName: "Ego Depletion", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did 'just this once' become more than once this week?",
              whyExplanation: "Exceptions accumulate. Spotting the third 'just this once' is where awareness lives.",
              biasName: "Present Bias", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you overestimate how much future-you would save?",
              whyExplanation: "Planning for future discipline beats planning for future income. Automate while you can.",
              biasName: "Overconfidence Bias", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you say yes to a group expense you'd have declined solo?",
              whyExplanation: "The cost of friction feels higher than the cost of money in that moment. It isn't.",
              biasName: "Social Proof", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'I deserve this' feature in a decision this week?",
              whyExplanation: "Reward thinking licences spending that doesn't survive tomorrow's review.",
              biasName: "Moral Licensing", biasCategory: "Self Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did an article or post influence a money choice today?",
              whyExplanation: "Recency + vividness bias picks over-represent themselves. The quiet data is usually the real data.",
              biasName: "Availability Heuristic", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you postpone checking a statement hoping it'd look better later?",
              whyExplanation: "Delayed looking compounds anxiety. The open action is disproportionately relieving.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'only $X per day' (instead of the total cost) make it feel smaller than it is?",
              whyExplanation: "Daily framing shrinks totals that are big annually. Annualise before you decide.",
              biasName: "Framing Effect", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you treat this month's unplanned expense as 'a one-off' again?",
              whyExplanation: "Unplanned-ness is itself the pattern. Budgeting for surprise is more accurate than pretending they're rare.",
              biasName: "Planning Fallacy", biasCategory: "Time Perception", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you stick with a pricier provider out of convenience?",
              whyExplanation: "Switching costs are usually one afternoon. Comfort costs are usually monthly.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did your 'fun money' feel like different money than your 'bills money'?",
              whyExplanation: "Mental buckets feel organised but cost clarity. All dollars weigh the same.",
              biasName: "Mental Accounting", biasCategory: "Money Psychology", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you take a small sure loss to avoid a bigger potential one?",
              whyExplanation: "Loss aversion is useful when real, expensive when imagined. Name the actual probability.",
              biasName: "Loss Aversion", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did you buy what was closest at hand rather than what was best?",
              whyExplanation: "Ease beats value more than we like to admit. A 60-second pause reorders the choice.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did an online recommendation change your mind mid-decision?",
              whyExplanation: "Reviews are social proof compressed. Three of them weigh more than statistics.",
              biasName: "Social Proof", biasCategory: "External Influence", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a discount make you buy something you didn't originally want?",
              whyExplanation: "Saving $20 on an unwanted $100 buy is still spending $80. The reference frame matters.",
              biasName: "Framing Effect", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did 'round up to $X' quietly stretch a purchase further?",
              whyExplanation: "Rounding is decision fatigue made visible. Exact numbers keep the frame honest.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you procrastinate a financial task that would take 10 minutes?",
              whyExplanation: "The task's weight grows with postponement. Ten minutes now is the cheapest version of the problem.",
              biasName: "Ostrich Effect", biasCategory: "Avoidance", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did 'we've always used this brand' override value comparison?",
              whyExplanation: "Loyalty is great when it's earned. When it's default, it's inertia with a story attached.",
              biasName: "Status Quo Bias", biasCategory: "Inertia", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did a recent expensive meal make tonight's spend feel 'small'?",
              whyExplanation: "Relative framing undercounts actual cost. Compare to budget, not to last night.",
              biasName: "Anchoring", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you finish a course or subscription just because you started?",
              whyExplanation: "Completion bias is sunk cost wearing a success costume. Ask if the remaining time is worth it today.",
              biasName: "Sunk Cost Fallacy", biasCategory: "Decision Making", difficulty: "intermediate", lastShown: nil),
        .init(id: UUID(), question: "Did 'let's just order in tonight' happen after a hard day?",
              whyExplanation: "Tiredness chooses convenience. Prepping easy evening options earlier neutralises the bias.",
              biasName: "Ego Depletion", biasCategory: "Decision Making", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you feel different about spending cash than tapping?",
              whyExplanation: "Physical pain of cash is real. Digital payments remove the signal. Weekly totals restore it.",
              biasName: "Denomination Effect", biasCategory: "Money Psychology", difficulty: "beginner", lastShown: nil),
        .init(id: UUID(), question: "Did you decide 'I'll think about it' and then still buy within an hour?",
              whyExplanation: "'Thinking about it' is often rehearsing the yes. Genuine delay means sleep on it.",
              biasName: "Present Bias", biasCategory: "Time Perception", difficulty: "beginner", lastShown: nil),
    ]
}
